spring:
  application:
    name: iRemodelAPI

  # Set default profile for development
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Common JPA settings across environments
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:dev_placeholder_replace_in_production_with_minimum_32_character_secret}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds

# Common logging settings
logging:
  level:
    org.springframework: INFO
    com.iremodelapi: INFO