# Production-specific settings
spring:
  # Persistent database in production
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate  # Use migrations in production, not auto-updates

  # Disable H2 console in production
  h2:
    console:
      enabled: false

# Production logging configuration
logging:
  level:
    root: ERROR
    com.iremodelapi: INFO
    org.springframework: WARN

# Add JWT Configuration (required for your auth system to work)
jwt:
  secret: ${JWT_SECRET}  # No default value in production!
  expiration: ${JWT_EXPIRATION:86400000}

# Additional production server hardening
server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never