spring:
  application:
    name: iremodelapi

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:iremodelapi
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driverClassName: org.h2.Driver

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

# Server Configuration (moved outside of spring namespace)
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

# JWT Configuration (moved outside of spring namespace)
jwt:
  secret: ${JWT_SECRET:placeholder_replace_in_production} # IMPORTANT: Override in production!
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds