spring:
  application:
    name: iremodelapi

  # Common JPA settings across environments
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  error:
    include-stacktrace: never

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:placeholder_replace_in_production} # Override in production!
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds

# Common logging settings
logging:
  level:
    org.springframework: INFO