
spring:
  datasource:
    url: jdbc:h2:mem:iremodelapi
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT Configuration - dev only - NEVER use these values in production
jwt:
  secret: ${JWT_SECRET:dev_only_secret_key_replace_in_production_minimum_32_chars}
  expiration: ${JWT_EXPIRATION:86400000}