# Production-specific settings
spring:
  # Persistent database in production
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    # Connection pool settings for production
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate  # Use migrations in production, not auto-updates
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Disable H2 console in production
  h2:
    console:
      enabled: false

# Production logging configuration
logging:
  level:
    root: WARN
    com.iremodelapi: INFO
    org.springframework: WARN
    org.hibernate: WARN

# JWT Configuration (required for your auth system to work)
jwt:
  secret: ${JWT_SECRET}  # No default value in production - MUST be provided!
  expiration: ${JWT_EXPIRATION:86400000}

# Additional production server hardening
server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
  # Production server settings
  compression:
    enabled: true
  http2:
    enabled: true

# Management endpoints (for monitoring)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never