spring:
  # Development database (H2)
  datasource:
    url: jdbc:h2:mem:iremodelapi
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  # Development JPA settings
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Recreates DB on each restart - good for dev
    show-sql: true

# Enhanced logging for development
logging:
  level:
    root: INFO
    com.iremodelapi: DEBUG  # Fixed package name
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE  # Updated for Hibernate 6.x
    org.springframework.security: DEBUG  # Helpful for JWT debugging

# Development error configuration
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

# JWT Configuration for development (longer secret for security)
jwt:
  secret: ${JWT_SECRET:development_secret_key_minimum_32_characters_long_for_hmac_sha256}
  expiration: ${JWT_EXPIRATION:86400000}